
name: Test

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Build succeed
          echo continuing to the deploy phase
  
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Build failed
          echo stopping the porcess
